### ISSUE TITLE
splitting on `'\\'` causes `IndexError: list index out of range` on linux

### ISSUE THREAD

**Issue by YAMLcase** [Heron-Repositories/Heron#6]
I get the following error when attempting to launch Heron on a linux box:
```
Traceback (most recent call last):
  File "/home/larryc/projects/Heron/Heron/gui/editor.py", line 641, in <module>
    node_selector = create_node_selector_window()
  File "/home/larryc/projects/Heron/Heron/gui/editor.py", line 587, in create_node_selector_window
    node_tree = generate_node_tree()
  File "/home/larryc/projects/Heron/Heron/gui/editor.py", line 61, in generate_node_tree
    while temp[i] != 'Heron':
IndexError: list index out of range
```

Root cause is splitting on backslash instead of forward slash.  I would suggest changing the following to `temp = d[0].split(os.path.sep)` to keep it platform agnostic:

https://github.com/Heron-Repositories/Heron/blob/d1bc956ede9a14edd3906a7ef38c10c2651e8ae0/Heron/gui/editor.py#L57

**Comment by georgedimitriadis** [comment]
Merged.

Thanks.

Good to know that the editor now works in a linux box.
